export const baseSpiritLabels: Record<string, string> = {
  gin: '金酒',
  rum: '朗姆酒',
  tequila: '龙舌兰',
  whiskey: '威士忌',
  brandy: '白兰地',
  vodka: '伏特加',
  pisco: '皮斯科',
  cachaca: '卡莎萨',
  wine: '葡萄酒',
  aperitif: '开胃酒',
  mixed: '混合基酒',
  multi: '多种基酒',
  none: '无基酒',
};

export const filterLabels: Record<string, string> = {
  gin: '金酒',
  rum: '朗姆酒',
  tequila: '龙舌兰',
  whiskey: '威士忌',
  brandy: '白兰地',
  vodka: '伏特加',
  pisco: '皮斯科',
  cachaca: '卡莎萨',
  wine: '葡萄酒',
  aperitif: '开胃酒',
  mixed: '混合基酒',
  multi: '多种基酒',
  none: '无基酒',
  agave: '龙舌兰植物香',
  bitter: '苦香',
  bitters: '苦香',
  bittersweet: '苦甜',
  anise: '茴香',
  apple: '苹果香',
  apricot: '杏香',
  berry: '浆果',
  bright: '明亮',
  citrus: '柑橘',
  coconut: '椰香',
  coffee: '咖啡',
  cola: '可乐',
  cocoa: '可可',
  creamy: '醇厚',
  cherry: '樱桃',
  cooling: '清凉',
  dry: '干爽',
  sweet: '甜润',
  sour: '酸爽',
  tart: '酸甜',
  herbal: '草本',
  floral: '花香',
  fresh: '清新',
  fruity: '果香',
  ginger: '姜香',
  grapefruit: '葡萄柚',
  grape: '葡萄香',
  minty: '薄荷',
  mint: '薄荷',
  nutty: '坚果',
  orange: '橙香',
  peach: '桃香',
  refreshing: '清爽',
  salty: '咸鲜',
  savory: '鲜味',
  silky: '丝滑',
  smoky: '烟熏',
  spiced: '香料',
  spicy: '辛香',
  sparkling: '起泡',
  strong: '劲烈',
  tannic: '单宁',
  tropical: '热带',
  'fortified-wine': '加强葡萄酒',
  honey: '蜂蜜',
  rich: '浓郁',
  warming: '暖香',
  woody: '木质',
  stirred: '搅拌',
  shaken: '摇和',
  built: '直接调制',
  'absinthe-rinse': '苦艾冲洗',
  cobbler: '鞋匠式',
  'crushed-ice': '碎冰',
  aperitivo: '餐前',
  'after-dinner': '餐后',
  blended: '搅打',
  brunch: '早午餐',
  fizz: '气泡',
  frozen: '冰冻',
  highball: '高球',
  hot: '热饮',
  'equal-parts': '等量结构',
  layered: '分层',
  long: '长饮',
  martini: '马天尼',
  muddled: '捣压',
  mule: '骡子',
  short: '短饮',
  sling: '斯林',
  punch: '潘趣',
  rocks: '加冰短饮',
  smash: '捣压',
  'spirit-forward': '烈酒主导',
  swizzled: '摇捣',
  tiki: '提基',
  up: '纯饮',
  classic: '经典',
};

export function labelFor(value: string): string {
  return filterLabels[value] || value;
}

export function displayDate(value: Date): string {
  return value.toISOString().slice(0, 10);
}
